# Generated by Django 2.0.3 on 2020-07-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_toppings', models.IntegerField(choices=[(0, 'Cheese'), (1, '1 Topping'), (2, '2 Topping'), (3, '3 Toppings'), (4, '4 Toppings/ Special')])),
                ('size', models.IntegerField(choices=[(0, 'Small'), (1, 'Large')])),
                ('menu_listing_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_price', to='menu.Menu')),
            ],
        ),
    ]
