# Generated by Django 2.0.3 on 2020-07-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('R', 'Regular Pizza'), ('S', 'Sicilian Pizza')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
