# Generated by Django 2.0.3 on 2020-07-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200715_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('size', models.IntegerField(choices=[(0, 'Small'), (1, 'Large')])),
                ('num_of_toppings', models.IntegerField(choices=[(0, 'No toppings'), (1, '1 topping'), (2, '2 toppings'), (3, '3 toppings'), (4, '4 toppings')])),
                ('menu_listing_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_item_price', to='menu.Menu')),
            ],
        ),
    ]
