# Generated by Django 2.0.3 on 2020-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topping', models.CharField(max_length=64)),
            ],
        ),
    ]
